defaults:
  - _self_
  - env: ???
  - wrappers: ???

wandb_project: "furuta2"
model_artifact: "model:latest"
render: False
nb_episodes: 3
record_video: True  # Set to True to record video of the first episode
