# scripts/configs/env/polimi.yaml
defaults:
  - _self_
  - robot: polimi_robot

_target_: furuta.rl.envs.furuta_real.FurutaReal
control_freq: 30  # You might want to adjust this based on your hardware capabilities
reward: "cos_alpha"
angle_limits: [null, null]  # degrees
speed_limits: [50, null]  # revolutions per second